"""AI Visibility Explorer — Streamlit home page.

Run with:  streamlit run app.py

This is the landing page. Use the sidebar to navigate to Data Input, the Visibility
Dashboard, Citation Analysis, Page Audit, the Customer Readout, and Limitations.
"""

from __future__ import annotations

import streamlit as st

from src import appkit
from src import metrics as M

st.set_page_config(
    page_title="AI Visibility Explorer",
    page_icon="🔎",
    layout="wide",
)

appkit.ensure_state()

st.title("🔎 AI Visibility Explorer")
st.caption(
    "Measure how often a brand appears across AI-search responses, how it compares "
    "with competitors, which sources get cited, and what to do next."
)

st.info(
    "**Demo data is synthetic.** The bundled responses were generated by a script for "
    "demonstration. They are **not** real outputs from ChatGPT, Claude, Gemini, "
    "Perplexity, or any other platform. Platform labels like *'ChatGPT (synthetic)'* "
    "make this explicit.",
    icon="ℹ️",
)

col1, col2 = st.columns([1, 1])
with col1:
    st.subheader("Get started in one click")
    st.write(
        "Load the bundled synthetic dataset (5 productivity brands, 22 prompts across "
        "all categories, 67 AI responses) to explore the full workflow immediately."
    )
    if st.button("🚀 Load demo data", type="primary", use_container_width=True):
        with st.spinner("Loading synthetic demo data and extracting mentions…"):
            appkit.set_data(appkit.load_demo_analysis())
            st.session_state["focal_brand"] = "Notion"
        st.success("Demo data loaded. Open **Visibility Dashboard** from the sidebar.")

    if appkit.has_data():
        if st.button("🗑️ Clear loaded data", use_container_width=True):
            appkit.set_data(appkit.get_data().__class__())
            st.session_state["page_audits"] = None
            st.rerun()

with col2:
    st.subheader("Or bring your own data")
    st.write(
        "Go to **Data Input** to create a project, add brands and prompts, and paste "
        "or upload AI responses as CSV. No API keys required."
    )
    st.page_link("pages/1_Data_Input.py", label="→ Go to Data Input", icon="📥")

st.divider()

# -- Current status ---------------------------------------------------------
data = appkit.get_data()
if appkit.has_data():
    n_runs = M.total_runs(data.response_runs)
    cite = M.citation_rate(data.citations, data.response_runs)
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Prompts", len(data.prompts))
    c2.metric("Responses", n_runs)
    c3.metric("Brands tracked", len(data.brands))
    c4.metric("Citation rate", f"{round(cite['citation_rate'] * 100)}%")
    if M.is_small_sample(n_runs):
        st.warning(
            f"⚠ Only {n_runs} responses loaded. Results are exploratory — see the "
            "**Limitations & Confidence** page before drawing conclusions."
        )
else:
    st.warning("No data loaded yet. Click **Load demo data** or use **Data Input**.")

st.divider()

with st.expander("What questions does this tool answer?"):
    st.markdown(
        """
1. How often is a brand mentioned across AI-search responses?
2. How does its visibility compare with competitors (share of voice)?
3. Which prompt topics and personas produce the strongest / weakest visibility?
4. Which brands are mentioned first or recommended most often?
5. Which websites and pages are cited?
6. Where are the content-coverage gaps?
7. How consistent are results across repeated prompt runs?
8. **What should the customer do next?** (see the Customer Readout page)
        """
    )

with st.expander("How the numbers are produced (transparency)"):
    st.markdown(
        """
- **Deterministic extraction** by default: case-insensitive brand matching (with
  user aliases) and URL parsing. Every number traces back to a concrete string match.
- **DuckDB** is used as the local SQL analytics engine over the loaded tables.
- **No black boxes, no invented findings.** The customer readout uses templated,
  metric-grounded language. An optional LLM narrative is available only if you add an
  API key, and it is clearly labelled as AI-generated.
        """
    )

st.caption("Portfolio project • Phase 1 MVP • Deterministic, offline-first, no paid APIs required.")
